version: '3.8'

services:
  web-site:
    image: nginx:alpine
    container_name: my-web-app
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - devops-net
    restart: always

  database:
    image: redis:alpine
    container_name: my-db
    networks:
      - devops-net
    restart: always

networks:
  devops-net:
    external: true
