version: '3.8'

services:
  web-site:
    image: nginx:alpine
    container_name: my-web-app
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - devops-net
    restart: always
    # --- ОБМЕЖЕННЯ ---
    deploy:
      resources:
        limits:
          cpus: '0.25'      # Не більше 25% одного ядра процесора
          memory: 64M       # Не більше 64 Мегабайт оперативки

  database:
    image: redis:alpine
    container_name: my-db
    networks:
      - devops-net
    restart: always
    # --- ОБМЕЖЕННЯ ---
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M

networks:
  devops-net:
    external: true
